# Generated by Django 5.0.14 on 2026-07-20 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('overload_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blocked_task_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deadline_proximity_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('historical_velocity_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('explanation_text', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='projects.project')),
            ],
            options={
                'db_table': 'risk_scores',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['project', 'computed_at'], name='risk_project_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkloadSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workload_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('underloaded', 'Underloaded'), ('balanced', 'Balanced'), ('overloaded', 'Overloaded'), ('critically_overloaded', 'Critically Overloaded')], max_length=30)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workload_snapshots',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user', 'computed_at'], name='workload_user_time_idx')],
            },
        ),
    ]
