# Generated by Django 5.0.14 on 2026-07-20 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('overloaded_member', 'Overloaded Member'), ('idle_member', 'Idle/Unassigned Member'), ('blocked_task', 'Blocked Task'), ('high_risk_project', 'High-Risk Project'), ('overdue_task', 'Overdue Task'), ('workload_imbalance', 'Workload Imbalance'), ('deadline_conflict', 'Deadline Conflict')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('explanation', models.TextField()),
                ('confidence_score', models.IntegerField(default=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('generated_by', models.CharField(choices=[('granite', 'Granite AI'), ('fallback_template', 'Fallback Template')], default='granite', max_length=50)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_accepted', to=settings.AUTH_USER_MODEL)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_current', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.project')),
                ('suggested_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_suggested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
