# Generated by Django 5.0.14 on 2026-07-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['project', 'status'], name='reco_project_status_idx'),
        ),
    ]
